# Generated by Django 4.2.20 on 2025-08-14 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurance',
            name='person',
        ),
        migrations.AddField(
            model_name='person',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('indefinite', 'Αορίστου χρόνου'), ('fixed_term', 'Ορισμένου χρόνου'), ('project', 'Έργου'), ('other', 'Άλλο')], max_length=15, verbose_name='Είδος σύμβασης'),
        ),
        migrations.AddField(
            model_name='person',
            name='disability_pension',
            field=models.BooleanField(default=False, verbose_name='Σύνταξη αναπηρίας'),
        ),
        migrations.AddField(
            model_name='person',
            name='employer_legal_form',
            field=models.CharField(blank=True, max_length=100, verbose_name='Νομική μορφή εργοδότη'),
        ),
        migrations.AddField(
            model_name='person',
            name='employer_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Εργοδότης'),
        ),
        migrations.AddField(
            model_name='person',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('employee', 'Υπάλληλος'), ('freelancer', 'Ελεύθερος Επαγγελματίας'), ('owner', 'Ιδιοκτήτης')], max_length=15, verbose_name='Εργασιακή σχέση'),
        ),
        migrations.AddField(
            model_name='person',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία πρόσληψης'),
        ),
        migrations.AddField(
            model_name='person',
            name='insurance_provider',
            field=models.CharField(blank=True, choices=[('ika', 'ΙΚΑ'), ('oga', 'ΟΓΑ'), ('etaa', 'ΕΤΑΑ'), ('special_funds', 'Ειδικά Ταμεία'), ('oaee', 'ΟΑΕΕ'), ('nat', 'ΝΑΤ'), ('public', 'ΔΗΜΟΣΙΟ'), ('tsmede', 'ΤΣΜΕΔΕ'), ('none', 'Δεν Έχω')], max_length=20, verbose_name='Φορέας κύριας ασφάλισης'),
        ),
        migrations.AddField(
            model_name='person',
            name='insurance_status',
            field=models.CharField(choices=[('insured', 'Ασφαλισμένος/η'), ('uninsured', 'Ανασφάλιστος/η'), ('indirectlyinsured', 'Έμμεσα Ασφαλισμένος/η')], default=1, max_length=20, verbose_name='Ασφάλιση'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, max_length=255, verbose_name='Επάγγελμα'),
        ),
        migrations.AddField(
            model_name='person',
            name='special_funds',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ειδικά ταμεία'),
        ),
        migrations.AddField(
            model_name='person',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ειδικότητα'),
        ),
        migrations.AddField(
            model_name='person',
            name='status',
            field=models.CharField(blank=True, choices=[('unemployed', 'Άνεργος/η'), ('employed', 'Εργαζόμενος/η'), ('retired', 'Συνταξιούχος'), ('housework', 'Οικιακά'), ('student', 'Φοιτητής'), ('retired_employed', 'Συντ & Εργαζ.'), ('other', 'Άλλο')], max_length=20, verbose_name='Εργασιακή κατάσταση'),
        ),
        migrations.AddField(
            model_name='person',
            name='unemployment_card',
            field=models.BooleanField(default=False, verbose_name='Κάρτα ανεργίας'),
        ),
        migrations.AddField(
            model_name='person',
            name='unemployment_registration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία εγγραφής ΟΑΕΔ'),
        ),
        migrations.AddField(
            model_name='person',
            name='widow_pension',
            field=models.BooleanField(default=False, verbose_name='Συντάξη χηρείας'),
        ),
        migrations.AddField(
            model_name='person',
            name='work_schedule',
            field=models.CharField(blank=True, choices=[('full_time', 'Πλήρης'), ('part_time', 'Μερική'), ('hourly', 'Ωρομίσθια'), ('seasonal', 'Εποχική')], max_length=15, verbose_name='Μορφή απασχόλησης'),
        ),
        migrations.AlterField(
            model_name='person',
            name='structure',
            field=models.CharField(choices=[('ΑΘΗΝΑ', 'ΑΘΗΝΑ'), ('ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ', 'ΑΛΕΞΑΝΔΡΟΥΠΟΛΗ'), ('ΘΕΣΣΑΛΟΝΙΚΗ', 'ΘΕΣΣΑΛΟΝΙΚΗ')], default='ΑΘΗΝΑ', max_length=50, verbose_name='Δομή'),
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='Insurance',
        ),
    ]
