# Generated by Django 4.2.20 on 2025-08-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_remove_insurance_person_person_contract_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='structure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.center', verbose_name='Δομή'),
        ),
    ]
