# Generated by Django 4.2.20 on 2025-08-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_alter_person_structure'),
    ]

    operations = [
    ]
