# Generated by Django 4.2.20 on 2025-08-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_auto_20250814_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='structure',
            field=models.CharField(blank=True, default=1, max_length=200, verbose_name='Διεύθυνση'),
            preserve_default=False,
        ),
    ]
