# Generated by Django 4.2.20 on 2025-08-20 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_auto_20250814_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='structure',
        ),
        migrations.AddField(
            model_name='person',
            name='center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='people', to='records.center', verbose_name='Δομή/Κέντρο'),
        ),
    ]
