# Generated by Django 4.2.20 on 2025-08-22 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_replace_structure_with_center'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medicalhistory',
            options={'verbose_name': 'Αναπηρία & ΚΕΠΑ', 'verbose_name_plural': 'Αναπηρία & ΚΕΠΑ'},
        ),
        migrations.AlterModelOptions(
            name='neoplasm',
            options={'verbose_name': 'Νεόπλασμα & Θεραπεία', 'verbose_name_plural': 'Νεοπλάσματα & Θεραπείες'},
        ),
        migrations.AlterModelOptions(
            name='requeststatus',
            options={'verbose_name': 'Κατηγορία αιτήματος', 'verbose_name_plural': 'Κατηγορίες αιτημάτων'},
        ),
        migrations.RemoveIndex(
            model_name='request',
            name='records_req_primary_224870_idx',
        ),
        migrations.RemoveField(
            model_name='actiontype',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='center',
            name='code',
        ),
        migrations.RemoveField(
            model_name='communicationchannel',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='comorbiditytype',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='employmentstatus',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='insuranceprovider',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='neoplasm',
            name='scheduled_treatment',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='organizationtype',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='request',
            name='primary_category',
        ),
        migrations.RemoveField(
            model_name='requestcategory',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='requeststatus',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='requesttype',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='therapytype',
            name='notes',
        ),
        migrations.AddField(
            model_name='neoplasm',
            name='scheduled_surgery',
            field=models.BooleanField(default=False, verbose_name='Προγραμματισμένη'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['category'], name='records_req_categor_ecb186_idx'),
        ),
    ]
