# Generated by Django 4.2.20 on 2025-08-22 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_medicalhistory_options_alter_neoplasm_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actiontype',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='communicationchannel',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='comorbiditytype',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='insuranceprovider',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='organizationtype',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='requestcategory',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='requeststatus',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='requesttype',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
        migrations.AlterField(
            model_name='therapytype',
            name='code',
            field=models.CharField(blank=True, max_length=40, unique=True, verbose_name='Κωδικός'),
        ),
    ]
