# Generated by Django 4.2.20 on 2025-08-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_alter_actiontype_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='outcome',
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(blank=True, choices=[('call', 'Κλήση'), ('email', 'Email'), ('referral', 'Παραπομπή')], max_length=20, null=True, verbose_name='Τύπος ενέργειας'),
        ),
    ]
