# Generated by Django 4.2.20 on 2025-08-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_populate_document_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ('category', 'sort_order', 'name'), 'verbose_name': 'Τύπος εγγράφου', 'verbose_name_plural': 'Τύποι εγγράφων'},
        ),
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Για έγγραφα που λήγουν (π.χ. ΚΕΠΑ, ταυτότητες)', null=True, verbose_name='Ημερομηνία λήξης'),
        ),
        migrations.AddField(
            model_name='document',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία έκδοσης'),
        ),
        migrations.AddField(
            model_name='document',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Σημειώσεις'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='category',
            field=models.CharField(choices=[('medical', 'Ιατρικά'), ('identity', 'Ταυτότητα & Προσωπικά'), ('financial', 'Οικονομικά & Ασφάλιση'), ('housing', 'Στέγαση & Κοινόχρηστα'), ('employment', 'Εργασιακά'), ('legal', 'Νομικά & Διοικητικά'), ('educational', 'Εκπαιδευτικά'), ('transport', 'Μεταφορά & Κινητικότητα'), ('request', 'Αιτήματα & Αλληλογραφία'), ('other', 'Άλλα')], default='other', max_length=20, verbose_name='Κατηγορία'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='code',
            field=models.CharField(default='', help_text='Μοναδικός κωδικός για το σύστημα (π.χ. kepa_certificate)', max_length=50, verbose_name='Κωδικός'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ενεργό'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='priority',
            field=models.CharField(choices=[('critical', 'Κρίσιμο'), ('important', 'Σημαντικό'), ('supporting', 'Υποστηρικτικό')], default='supporting', max_length=15, verbose_name='Προτεραιότητα'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='renewal_months',
            field=models.PositiveIntegerField(blank=True, help_text='Πόσους μήνες πριν τη λήξη να προειδοποιηθεί', null=True, verbose_name='Μήνες ανανέωσης'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='requires_renewal',
            field=models.BooleanField(default=False, help_text='Αν το έγγραφο έχει ημερομηνία λήξης', verbose_name='Χρειάζεται ανανέωση'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Σειρά εμφάνισης'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Όνομα'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['person', 'document_type'], name='records_doc_person__37307a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expiry_date'], name='records_doc_expiry__7e681a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_verified'], name='records_doc_is_veri_0ccfad_idx'),
        ),
    ]
