# Generated by Django 4.2.9 on 2025-08-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0012_alter_documenttype_options_document_expiry_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttype',
            options={'ordering': ('name',), 'verbose_name': 'Τύπος εγγράφου', 'verbose_name_plural': 'Τύποι εγγράφων'},
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='category',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='code',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='renewal_months',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='requires_renewal',
        ),
        migrations.RemoveField(
            model_name='documenttype',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Όνομα'),
        ),
    ]
