# Generated by Django 4.2.9 on 2026-03-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_alter_documenttype_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='birth_year',
        ),
        migrations.AddField(
            model_name='person',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Ημερομηνία γέννησης'),
        ),
    ]
