# Generated by Django 4.2.9 on 2026-03-12 11:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_remove_person_birth_year_person_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actionattachment',
            name='action',
        ),
        migrations.RemoveIndex(
            model_name='action',
            name='records_act_require_5e224a_idx',
        ),
        migrations.RemoveField(
            model_name='action',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='action',
            name='contact_type',
        ),
        migrations.RemoveField(
            model_name='action',
            name='external_org',
        ),
        migrations.RemoveField(
            model_name='action',
            name='manual_contact_email',
        ),
        migrations.RemoveField(
            model_name='action',
            name='manual_contact_name',
        ),
        migrations.RemoveField(
            model_name='action',
            name='manual_contact_phone',
        ),
        migrations.RemoveField(
            model_name='action',
            name='manual_contact_position',
        ),
        migrations.RemoveField(
            model_name='action',
            name='manual_org_name',
        ),
        migrations.RemoveField(
            model_name='action',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='action',
            name='referral_type',
        ),
        migrations.RemoveField(
            model_name='action',
            name='requires_follow_up',
        ),
        migrations.AddField(
            model_name='action',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='action',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Όνομα επικοινωνίας'),
        ),
        migrations.AddField(
            model_name='action',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Τηλέφωνο'),
        ),
        migrations.AddField(
            model_name='action',
            name='contact_role',
            field=models.CharField(blank=True, max_length=100, verbose_name='Θέση'),
        ),
        migrations.AddField(
            model_name='action',
            name='org_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Φορέας'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Ημερομηνία'),
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('CONTACT', 'Επικοινωνία'), ('REFERRAL', 'Παραπομπή'), ('DOCUMENT', 'Έγγραφο'), ('FOLLOWUP', 'Παρακολούθηση')], default='CONTACT', max_length=20, verbose_name='Τύπος ενέργειας'),
        ),
        migrations.AlterField(
            model_name='action',
            name='direction',
            field=models.CharField(blank=True, choices=[('TO', 'Προς'), ('FROM', 'Από')], default='TO', max_length=10, verbose_name='Κατεύθυνση'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='action',
            name='result',
            field=models.TextField(blank=True, verbose_name='Αποτέλεσμα'),
        ),
        migrations.AddIndex(
            model_name='action',
            index=models.Index(fields=['follow_up_date'], name='records_act_follow__19cbcc_idx'),
        ),
        migrations.DeleteModel(
            name='ActionAttachment',
        ),
    ]
