# Generated by Django 4.2.9 on 2026-03-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0016_remove_person_birth_date_person_birth_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='neoplasm',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='neoplasm',
            name='category_label',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='neoplasm',
            name='icd10_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='neoplasm',
            name='type_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='neoplasm',
            name='icd10_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='records.icd10code', verbose_name='Είδος'),
        ),
    ]
