# Generated by Django 4.2.9 on 2026-04-23 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0017_alter_neoplasm_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_intake',
            field=models.BooleanField(default=False, verbose_name='Εγγραφή εισαγωγής'),
        ),
    ]
